spring:
  datasource:
    url: jdbc:postgresql://localhost:5454/orderdb
    username: user
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:9092
server:
  source-db-host: localhost
  source-db-port: 5454
  source-db-user: user
  source-db-password: root
  source-db-name: orderdb
