version: "3.7"
networks:
  kafka-net:
    driver: bridge
services:
  postgres-1:
    container_name: source_db
    image: debezium/postgres:13
    ports:
      - 5454:5432
    networks:
      - kafka-net
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=orderdb
      - PGPASSWORD=postgrespw

  postgres-2:
    container_name: target_db
    image: debezium/postgres:13
    ports:
      - 5455:5432
    networks:
      - kafka-net
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=orderdb
      - PGPASSWORD=postgrespw
  zookeeper:
    container_name: zookeeper
    image: 'zookeeper:latest'
    networks:
      - kafka-net
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    container_name: kafka
    image: 'bitnami/kafka:latest'
    networks:
      - kafka-net
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://10.168.2.42:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://:9092
  debezium:
    container_name: debezium
    image: debezium/connect:latest
    networks:
      - kafka-net
    environment:
      BOOTSTRAP_SERVERS: 10.168.2.42:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: connect_configs
      OFFSET_STORAGE_TOPIC: connect_offsets
      OFFSET_FLUSH_INTERVAL_MS: 20000
      OFFSET_FLUSH_TIMEOUT_MS: 10000
    ports:
      - 8083:8083
    depends_on:
      - zookeeper
      - kafka
  debezium-ui:
    container_name: debezium-ui
    image: 'debezium/debezium-ui:latest'
    networks:
      - kafka-net
    ports:
      - '8081:8080'
    environment:
      - KAFKA_CONNECT_URIS=http://debezium:8083
